"""In-memory store of live rooms, keyed by name.

Replaces the legacy module-level ``rooms = {}`` global with an injected object,
so the transport resolves a ``Room`` to hand to ``GameService`` and nothing
reaches for a global. In-memory now; a Redis-backed implementation can satisfy
the same surface later without touching callers.
"""

from app.domain.room import Room


class RoomRegistry:
    def __init__(self):
        self._rooms: dict[str, Room] = {}

    def get(self, name: str) -> Room | None:
        return self._rooms.get(name)

    def create(self, name: str) -> Room | None:
        """Store a new room under ``name``; return ``None`` if it's already taken.

        Distinct from a get-or-create: minting an autogenerated room code must
        fail on collision so the caller retries with a fresh code rather than
        joining an unrelated room.
        """
        if name in self._rooms:
            return None
        room = Room(name)
        self._rooms[name] = room
        return room

    def remove(self, name: str) -> None:
        self._rooms.pop(name, None)
